apiVersion: apps/v1
kind: Deployment
metadata:
  name: sysapi
  labels:
    app: sysapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sysapi
  template:
    metadata:
      labels:
        app: sysapi
    spec:
      containers:
      - name: sysapi 
        image: REGISTRY.rsyslab.com:5000/sysapi:latest
        ports:
        - containerPort: 8000
